---
- hosts: all
  handlers:
    - name: restart_apache
      service:
        name: apache2
        state: restarted
      become: yes
  tasks: 
    - name: Instalacao de Dependencias
      ansible.builtin.apt:
        pkg:
          - apache2
          - ghostscript
          - libapache2-mod-php
          - mysql-server
          - php
          - php-bcmath
          - ghostscript
          - libapache2-mod-php
          - mysql-server
          - php
          - php-bcmath
          - php-curl
          - php-imagick
          - php-intl
          - php-json
          - php-mbstring
          - php-mysql
          - php-xml
          - php-zip
          - python3-pymysql
        state: latest
        update_cache: yes
      become: yes
    - name: Criacao de diretorio
      ansible.builtin.file:
        path: /srv/www
        state: directory
        mode: '0755'
        owner: www-data
        group: www-data
      become: yes
    - name: Download e desempacotamento do Wordpress
      ansible.builtin.unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: /srv/www
        remote_src: yes
      become: yes
    - name: Copia da configuracao do Wordpress
      ansible.builtin.copy:
        src: files/wordpress.conf
        dest: /etc/apache2/sites-available/000-default.conf
      become: yes
      notify:
        - restart_apache
    - name: Criacao o banco de dados MySQL
      community.mysql.mysql_db:
        name: wordpress_db
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock
      become: yes